version: '3.8'

services:
  mimicmotion:
    build:
      context: .
      dockerfile: Dockerfile.fast
    image: mimicmotion:fast
    container_name: mimicmotion-fast
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONUNBUFFERED=1
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:256
      - HF_ENDPOINT=https://hf-mirror.com
    volumes:
      # Mount directories
      - ./outputs:/app/outputs
      - ./configs:/app/configs
      - ./assets:/app/assets
      - ./models:/app/models
    command: ["conda", "run", "-n", "mimicmotion", "python", "inference.py", "--inference_config", "configs/test.yaml"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]